#!/bin/bash

rm -f ~/.bashrc
ln -sf ~/Work/ralphjzhang/dotfiles/bash/.bashrc ~/
rm -f ~/.tmux.conf
ln -sf ~/Work/ralphjzhang/dotfiles/tmux/.tmux.conf ~/
rm -f ~/.tmuxinator.yml
ln -sf ~/Work/ralphjzhang/dotfiles/tmux/.tmuxinator.yml ~/

rm -f ~/.vimrc
ln -sf ~/Work/ralphjzhang/dotfiles/vim/.vimrc ~/
rm -f ~/.ycm_extra_conf.py
ln -sf ~/Work/ralphjzhang/dotfiles/vim/.ycm_extra_conf.py ~/
mkdir -p ~/.vim/bundle
# git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

