#!/bin/bash

function yum() {
  # if we get here, git should have be installed, but just make sure
  sudo yum -y install git tree tmux gcc gcc-c++ vim
  sudo yum -y socat htop iperf
  pip install tmuxp
}

function shell() {
  rm -f ~/.bashrc
  ln -sf ~/Work/ralphjzhang/dotfiles/bash/.bashrc ~/
  rm -f ~/.tmux.conf
  ln -sf ~/Work/ralphjzhang/dotfiles/tmux/.tmux.conf ~/
  rm -rf ~/.tmuxp
  ln -sf ~/Work/ralphjzhang/dotfiles/tmux/tmuxp ~/.tmuxp
}

function vim() {
  rm -f ~/.vimrc
  ln -sf ~/Work/ralphjzhang/dotfiles/vim/.vimrc ~/
  rm -f ~/.ycm_extra_conf.py
  ln -sf ~/Work/ralphjzhang/dotfiles/vim/.ycm_extra_conf.py ~/
  rm -f ~/.vimshrc
  ln -sf ~/Work/ralphjzhang/dotfiles/vim/.vimshrc ~/
  mkdir -p ~/.vim/bundle
  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
}

function ycm() {
  cd ~/.vim/bundle/YouCompleteMe
  sudo yum -y install python-devel
  ./install.py --clang-completer
}


function all() {
  yum
  shell
  vim
  ycm
}

# main entry: call function directly by name
$1

