session_name: yi-vm
root: ~/
windows:
  - commands:
      layout: even-horizontal
      panes:
        - cd
        - cd Work
  - code: cd ~/Work/infra/yi
  - view: cd ~/Work/infra/yi
  - prod: 
      layout: main-vertical
      panes:
        - ssh prod-cindac
        - ssh prod-cindac
        - ssh prod-cindac

